### ISSUE TITLE
Dúvida sobre utilização

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [kelvins/Algoritmos-e-Estruturas-de-Dados#12]
boa tarde, ótima iniciativa do criador, esse repositório é para contribuirmos com algoritmos diferentes de analise de dados ? ou é para incluirmos o código dos mesmos ? 
grato .

**Comment by kelvins** [comment]
Opa, e ai @LaurianoElmiroDuarte, beleza? Cara toda contribuição é bem vinda.
A ideia é disponibilizar os principais algoritmos estudados na academia em diferentes linguagens.
Existem várias formas de contribuir:
  - Incluindo códigos em diferentes linguagens para algoritmos já existentes.
  - Atualizando/Melhorando códigos já existentes no repo.
  - Incluindo novos algoritmos que sejam relevantes para os estudos de algoritmos e estruturas de dados.
  - Melhorando a documentação do repo (e.g. README, COMO CONTRIBUIR, etc).

Os algoritmos "extras" são casos a parte, geralmente vistos em maratonas de programação e/ou desafios de engenharia de software.
