### ISSUE TITLE
Adicionar Elixir a lista de linguagens

### ISSUE THREAD

**Issue by MarceloLuisDantas** [kelvins/Algoritmos-e-Estruturas-de-Dados#125]
Sei que por um tempo, a coluna de Elixir será um setor vazio semelhante a Pascal, porem tenho certeza que assim com Rust foi para mim, poderá ser algo útil para dev's novatos em Elixir que estão meio perdido. Além de que se tem Pascal Imagino que terá algum publico para Elixir também.  Eu sei que a tabela já esta completa, porem acho que nesse caso deixar o README um pouco mais feio para ter mais variedade é um boa troca. 
No momento em que eu postar esta Issue estarei fazendo um pull request com as modificações necessárias, junto ao algoritmo de Fatorial Recursivo em Elixir para a seção não ficar 100% vazia.

**Comment by MarceloLuisDantas** [comment]
Concordo, modificar as listas para  HTML pode ser um tanto complicado, porem seria mais fácil de manipular no futuro de fato. Vou trabalhar nisso e hoje a noite irei abrir Pull Request com as modificações.

**Comment by kelvins** [comment]
Valeu @MarceloLuisDantas, criei outras 2 issues relacionadas aos pontos levantados acima:
- https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/issues/127
- https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/issues/128

Acredito que assim fica mais organizado e é possível tratar as coisas de forma separada e com PRs específicos para cada uma. Assim, essa issue fica com a responsabilidade apenas de inclusão de Elixir e pode ser tratada posteriormente a alteração da tabela.

**Comment by kelvins** [comment]
Resolvido no PR https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/pull/131
