### ISSUE TITLE
Estrutura de Dados - Hash Table 

### ISSUE THREAD

**Issue by 64bits-Camargo** [kelvins/Algoritmos-e-Estruturas-de-Dados#139]
Olá, 

Queria contribuir com estrutura de dados de Hash Table em python, posteriormente posso fazer das outras linguagens.

**Comment by kelvins** [comment]
Claro, seja muito bem vindo 🚀

**Comment by kelvins** [comment]
Resolvido no PR https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/pull/140
