### ISSUE TITLE
Adição de algoritmos em Kotlin.

### ISSUE THREAD

**Issue by Alfredo-Paes** [kelvins/Algoritmos-e-Estruturas-de-Dados#152]
Olá! Seria bastante interessante a adição de algoritmos em Kotlin, sendo que, é uma linguagem em uso crescente e, a Google adotou a posição "Kotlin first". Além do mais, é uma linguagem que aborda tanto o paradigma Orientado a Objetos quanto, paradigma funcional e, é de leitura mais simples(se comparando a Java), remetendo até mesmo ao Swift. Portanto, concluo que, seria bastante interessante
a adição dessa linguagem ao repositório, além de outras mais características que possam ser descritas.

Grato pela a atenção.

**Comment by kelvins** [comment]
Olá @Alfredo-Paes, valeu por abrir a issue.
Pessoalmente eu não tenho experiência com Kotlin mas se tivermos pessoas dispostas a contribuir com algoritmos nessa linguagem eu sou a favor de incluir sim. Se tivermos algo como 3+ algoritmos acho que já poderíamos incluir sem problema algum.

**Comment by Alfredo-Paes** [comment]
Olá @kelvins , fico agradecido por responder. Já estou trabalhando em cima de alguns algoritmos em Kotlin, são até mesmo baseados nos algoritmos já existentes no repositório. Caso eu faça um pull-request, existe a possibilidade de você avaliar se está no padrão do repositório?

Desde já, grato por sua atenção e resposta.

**Comment by kelvins** [comment]
Claro 👍

**Comment by Alfredo-Paes** [comment]
Olá @kelvins ! Estou com uma branch criada a partira da **main**, para a implementação de algoritmos Kotlin. Existe a possibilidade de obter a autorização para a criação de **pull-requests**?

Grato pela a atenção!

**Comment by kelvins** [comment]
Olá @Alfredo-Paes, a princípio qualquer pessoa pode abrir PR, vc está tendo problema/erro específico?

**Comment by Alfredo-Paes** [comment]
@kelvins criei uma branch a partir da **main**, porém, ao subir a mesma(**git push origin algoritmo-kotlin**) para a criação do PR, dá problema com permissão.

`ERROR: Permission to kelvins/Algoritmos-e-Estruturas-de-Dados.git denied to Alfredo-Paes.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by kelvins** [comment]
Hm, por acaso vc clonou o repositório ou fez um fork? O ideal seria fazer um fork e abrir o PR a partir do seu fork (mais infos [aqui](https://docs.github.com/pt/get-started/quickstart/contributing-to-projects)).

**Comment by Alfredo-Paes** [comment]
@kelvins fico agradecido por seu feedback e instrução para a criação do **Pull Request**. De fato, estava fazendo de forma errônea, consequência de não estar habituado da criação de branchs, commit's e PR's derivando do fork. Mais uma vez, agradecido pela a assistência.

**Comment by kelvins** [comment]
Valeu pela contribuição @Alfredo-Paes, fique a vontade para abrir novos PRs com algoritmos em Kotlin.
