### ISSUE TITLE
Converter código e comentários para Inglês

### ISSUE THREAD

**Issue by kelvins** [kelvins/Algoritmos-e-Estruturas-de-Dados#160]
Apesar do repositório estar em Português acredito que seria mais interessante se tanto o código quanto os comentários no código estivessem em Inglês, pois este é o padrão adotado por praticamente todas as empresas/pessoas.

**Comment by ricardocarva** [comment]
Bom dia, Kelvin. Comecei a traduzir alguns algoritmos de c/c++ para o ingles.

**Comment by ricardocarva** [comment]
Acredito que com isso, temos todos os algoritmos de cpp traduzidos e suas referencias. Acho que poderiamos ter esse issue traduzido em ingles tambem assim como o contributing file. Dessa forma, convidamos pessoas que nao falam portugues para contribuir tambem.

**Comment by kelvins** [comment]
Acho ótimo. Fique a vontade se quiser converter a issue para Inglês ou até quebrar em múltiplas issues por linguagem de programação.

**Comment by ricardocarva** [comment]
Feito, @kelvins. Abri varios issues por linguagens de programacao. Voce consegue colocar as tagas de good-first-issue e help wanted? Talvez um hacktoberfest cairia bem tambem

**Comment by kelvins** [comment]
Boa, valeu @ricardocarva, vou adicionar os labels e estou fechando esse PR em favor dos novos que foram criados.
