### ISSUE TITLE
Convertir código y comentarios en español 

### ISSUE THREAD

**Issue by alan1996colo** [kelvins/Algoritmos-e-Estruturas-de-Dados#161]
Se puede crear otro branch con los mismos algoritmos con comentarios explicados en español.

**Comment by kelvins** [comment]
Hola @alan1996colo, gracias por la sugerencia pero creo que deberíamos mantener todo en Inglés. En mi opinión podríamos tener un archivo `CONTRIBUTING.md` en varios idiomas, pero el código y los comentarios deberían estar en Inglés, que es el “idioma universal” en el área de desarrollo de software.
