### ISSUE TITLE
Error executing AlgoritmoDijkstra.c code

### ISSUE THREAD

**Issue by BDadmehr0** [kelvins/Algoritmos-e-Estruturas-de-Dados#203]
**Error** :

m.c: In function ‘Dijkstra’:
m.c:42:5: error: unknown type name ‘bool’
   42 |     bool visitados[n]; // Variável que guarda true para os vértices visitados
      |     ^~~~
m.c:37:1: note: ‘bool’ is defined in header ‘<stdbool.h>’; did you forget to ‘#include <stdbool.h>’?
   36 | #include <stdio.h>
  +++ |+#include <stdbool.h>
   37 | //#include <stdbool.h>
m.c:59:28: error: ‘true’ undeclared (first use in this function)
   59 |           visitados[min] = true; // Marca o valor a posição do minimo como visitado
      |                            ^~~~
m.c:59:28: note: ‘true’ is defined in header ‘<stdbool.h>’; did you forget to ‘#include <stdbool.h>’?
m.c:59:28: note: each undeclared identifier is reported only once for each function it appears in

**solution** :‌

Add this library to the code `#include <stdbool.h>`

**Comment by kelvins** [comment]
Thanks a lot @BDadmehr0. Fixed by commit f12e7b7556a2912e8906e54b5b194b8e0b8ba451
