### ISSUE TITLE
In dark mode, the Rust icon is almost unnoticeable

### ISSUE THREAD

**Issue by leandronsp** [kelvins/Algoritmos-e-Estruturas-de-Dados#224]
While using dark mode on Github, the Rust icon is unnoticeable, which gives the impression that the exercise is missing the Rust implementation.

Tried to use inline CSS [in this PR](https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/pull/215), but it's not ideal since it wouldn't work well in other versions. 

Ideally, we should overcome that by changing directly the SVG, maybe.

<img width="806" alt="Screenshot 2023-10-03 at 11 04 05" src="https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/assets/385640/ea8c23a6-ea15-434a-be66-e17d5df82e56">

**Comment by IndranjanaChatterjee** [comment]
I would like to work on this issue to achieve the required changes using dark mode on Github . Please assign it to me.
