### ISSUE TITLE
Update README logos

### ISSUE THREAD

**Issue by kelvins** [kelvins/Algoritmos-e-Estruturas-de-Dados#228]
I recently added new SVG logos to a `logos` folder in the project root.
It would be nice to update all SVG links from the `README.md` to point to these new logos.

**Comment by jfmartinz** [comment]
> I recently added new SVG logos to a `logos` folder in the project root. It would be nice to update all SVG links from the `README.md` to point to these new logos.

Just clarifiying. Like this `logos/c.svg`. Also the task is to update all the svgs to the new path which is logo/..

**Comment by jfmartinz** [comment]
If yes please assign this issue to me. thanks

**Comment by kelvins** [comment]
Yes, but I believe we must include a dot at the beginning, like replacing `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg` by `./logos/cplusplus.svg`.

**Comment by jfmartinz** [comment]
> Yes, but I believe we must include a dot at the beginning, like replacing `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg` by `./logos/cplusplus.svg`.

I think you forgot to add a svg for this icon:
![image](https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/assets/129386460/c553617a-fc8f-419d-b7a2-c31ebfb03da9)

I don't see anything on the svgs

**Comment by jfmartinz** [comment]
only cplusplus
