### ISSUE TITLE
Converter algoritmos de Python2 para Python3

### ISSUE THREAD

**Issue by kelvins** [kelvins/Algoritmos-e-Estruturas-de-Dados#34]
Converter algoritmos de Python2 para Python3 aplicando PEP8.

**Comment by lukelima** [comment]
Creio que o **PR** #39  resolva essa issue

**Comment by kelvins** [comment]
Resolvido com o PR https://github.com/kelvins/Algoritmos-e-Estruturas-de-Dados/pull/39 :+1:
