### ISSUE TITLE
Ajuda Kelvin

### ISSUE THREAD

**Issue by yuriifreire** [kelvins/Algoritmos-e-Estruturas-de-Dados#4]
Fala ai Kelvin, desculpa ta usando a ISSUE pra isso, mas preciso fazer essa lista encadeada junto de pilhas e fila + CRUD, tem como ajudar?

**Comment by kelvins** [comment]
Opa, e ai Yuri, posso tentar te ajudar sim. Pode entrar em contato comigo por e-mail (kelvinpfw@gmail.com) explicando o que você precisa fazer.
