### ISSUE TITLE
Busca sequencial e busca sequencial recursiva em C

### ISSUE THREAD

**Issue by ed1rac** [kelvins/Algoritmos-e-Estruturas-de-Dados#40]
- Busca Sequencial em C
- Busca recursiva em C

**Comment by ed1rac** [comment]
- Já estou com os arquivos prontos.
Posso fazer em Java também.

**Comment by kelvins** [comment]
Boa, valeu @ed1rac, fique a vontade para abrir o PR.
Se puder abrir os PRs separados por linguagem ou mesmo por algoritmo eh melhor, fica mais facil/rapido de revisar e mergear.

**Comment by ed1rac** [comment]
Ok
_________________________________
Edkallenn Silva de Lima
Agente de Polícia Federal - Mat. 16777
Chefe do NTI/SR/AC - (68) 3212-1211
lima.esl@pf.gov.br
---
*"Que sei eu do que serei, eu que não sei o que sou?"*
- Álvaro de Campos, heterônimo de Fernando Pessoa



Em sáb., 23 de mai. de 2020 às 11:22, Kelvin S. do Prado <
notifications@github.com> escreveu:

**Comment by kelvins** [comment]
Vou fechar a issue, mas fique a vontade para abrir o PR se ainda tiver interesse.
