### ISSUE TITLE
Os imports do main.go estão errados

### ISSUE THREAD

**Issue by heitor582** [kelvins/Algoritmos-e-Estruturas-de-Dados#60]
![image](https://user-images.githubusercontent.com/58075535/98825637-7cb2c000-2413-11eb-9a5c-6e4889463e8d.png)
![image](https://user-images.githubusercontent.com/58075535/98825788-ab309b00-2413-11eb-8acd-821eb2595cba.png)
Bom dia, como vou puxar de GoLang se a pasta chama go, posso alterar e mandar num pr?

**Comment by kelvins** [comment]
Claro, por favor. Antigamente era `GoLang`, em algum momento mudou e acabou ficando isso para trás.

**Comment by heitor582** [comment]
Okok vou mandar o pr
