### ISSUE TITLE
[Swift] [Rust] Adicionar Swift e Rust nas linguagens

### ISSUE THREAD

**Issue by matheustorresii** [kelvins/Algoritmos-e-Estruturas-de-Dados#62]
## Adicionar Swift e Rust nas linguagens
Bom dia, boa tarde, boa noite, eu estava pensando em adicionar as linguagens ``Swift`` e ``Rust`` às linguagens disponíveis neste repositório, atualmente fiz 10 dos algoritmos presentes em Swift e um amigo meu (@heitor582) concluiu mais 10 em Rust, e acho que seria interessante a inclusão do Swift e do Rust, diante ao crescimento de ambas linguagens.

**Comment by kelvins** [comment]
Olá @matheustorresii, seria uma boa, se puderem incluir isso seria fantástico. Com base nisso, tenho duas sugestões:
- Se quebrar a formatação da tabela do README devido ao número de colunas podemos abreviar `Javascript` para `JS`.
- Sugiro abrir um PR para cada algoritmo, assim fica mais fácil de revisar e mergear gradualmente.

Valeu
