### ISSUE TITLE
Adicionar a opção de criar algoritmos em Dart

### ISSUE THREAD

**Issue by snlucas** [kelvins/Algoritmos-e-Estruturas-de-Dados#93]

**Comment by kelvins** [comment]
Olá @snlucas, como essa issue foi aberta a mais de 1 ano e aparentemente não tivemos mais pessoas interessadas, e eu pessoalmente também não tenho interesse em desenvolver em Dart, estou fechando a issue. Se fizer sentido podemos reabrir em algum momento futuro. De toda forma, agradeço pela contribuição.

**Comment by snlucas** [comment]
> Olá @snlucas, como essa issue foi aberta a mais de 1 ano e aparentemente não tivemos mais pessoas interessadas, e eu pessoalmente também não tenho interesse em desenvolver em Dart, estou fechando a issue. Se fizer sentido podemos reabrir em algum momento futuro. De toda forma, agradeço pela contribuição.

Tranquilo, @kelvins 👍
