### ISSUE TITLE
Booyer Moore e Compressão

### ISSUE THREAD

**Issue by hansbonini** [kelvins/Algoritmos-e-Estruturas-de-Dados#97]
Seria interessante adicionar busca recursiva com Boyer Moore e algoritmos relacionados a compressão de dados como Ring Buffer, LZ, Huffman.

**Comment by kelvins** [comment]
Excelentes sugestões @hansbonini, se tiver disponibilidade e quiser contribuir fique à vontade, toda contribuição é bem vinda 😁

**Comment by kelvins** [comment]
Como já temos Huffman e LZ77, criei uma nova issue específica para ring buffer, por conta disso vou fechar essa.

Valeu pelas sugestões @hansbonini 👍
